language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
script: npm run build # Here you could also run the build step of your application
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now ./build --token $NOW_TOKEN --public --name ynood --local-config=now.json
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $NOW_TOKEN --public && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true