export const mockYnoodAccounts = {
  data: {
    accounts: [
      {
        debt_id: 1,
        ynab_guid: '4f8978af-dc34-4c45-bfda-5fb82925cb93',
        nickname: 'Mortgage',
        current_balance: 135789,
        highest_balance: 135789,
        interest_rate: 3.4,
        next_due_date: '2018-09-01',
        credit_limit: 0,
        minimum_payment: 233,
        active: 1,
        planned_payment_this_month: 233,
        planned_payment_next_month: 233,
        scheduled_payoff_date: '2033-05-01'
      },
      {
        debt_id: 1,
        ynab_guid: '4f8978af-dc34-4c45-bfda-5fb82925cb93-unsynced',
        nickname: 'Mortgage',
        current_balance: 135789,
        highest_balance: 135789,
        interest_rate: 3.4,
        next_due_date: '2018-09-01',
        credit_limit: 0,
        minimum_payment: 233,
        active: 1,
        planned_payment_this_month: 233,
        planned_payment_next_month: 233,
        scheduled_payoff_date: '2033-05-01'
      },
      {
        debt_id: 2,
        nickname: 'American Express',
        current_balance: 2342.33,
        highest_balance: 2342.33,
        interest_rate: 15.99,
        next_due_date: '2018-09-09',
        credit_limit: 0,
        minimum_payment: 50,
        active: 1,
        planned_payment_this_month: 50,
        planned_payment_next_month: 767,
        scheduled_payoff_date: '2018-12-01'
      }
    ]
  }
}

export const mockYnabBudget = {
  data: {
    budget: {
      id: 'b1e3fe83-611f-4af8-8805-c9fea0786e74',
      name: 'My Budget',
      last_modified_on: '2018-08-29T19:18:44.000Z',
      date_format: { format: 'MM/DD/YYYY' },
      currency_format: {
        iso_code: 'USD',
        example_format: '123,456.78',
        decimal_digits: 2,
        decimal_separator: '.',
        symbol_first: true,
        group_separator: ',',
        currency_symbol: '$',
        display_symbol: true
      },
      first_month: '2018-08-01',
      last_month: '2018-09-01',
      accounts: [
        {
          id: '575ab9b3-d2cc-4e9b-a7fa-c1b9caf937b0',
          name: 'American Express',
          type: 'creditCard',
          on_budget: true,
          closed: false,
          note: null,
          balance: -2342330,
          cleared_balance: -2342330,
          uncleared_balance: 0,
          deleted: false
        },
        {
          id: '4f8978af-dc34-4c45-bfda-5fb82925cb93',
          name: 'Mortgage',
          type: 'otherLiability',
          on_budget: false,
          closed: false,
          note: null,
          balance: -135789000,
          cleared_balance: -135789000,
          uncleared_balance: 0,
          deleted: false
        },
        {
          id: '4f8978af-dc34-4c45-bfda-5fb82925cb93-unsynced',
          name: 'Mortgage',
          type: 'otherLiability',
          on_budget: false,
          closed: false,
          note: null,
          balance: -125789000,
          cleared_balance: -125789000,
          uncleared_balance: 0,
          deleted: false
        }
      ],
      payees: [
        {
          id: 'f3b96458-b9ed-48d4-8781-52a7ef1ad9e4',
          name: 'Starting Balance',
          transfer_account_id: null,
          deleted: false
        },
        {
          id: '5c5acefa-f833-454b-8095-55247ba75609',
          name: 'Manual Balance Adjustment',
          transfer_account_id: null,
          deleted: false
        },
        {
          id: 'd4908e21-da7d-4f7e-b711-7aa01bf247a2',
          name: 'Reconciliation Balance Adjustment',
          transfer_account_id: null,
          deleted: false
        },
        {
          id: '32334fd1-5405-4ebb-ba14-38d750a2fa94',
          name: 'Transfer : American Express',
          transfer_account_id: '575ab9b3-d2cc-4e9b-a7fa-c1b9caf937b0',
          deleted: false
        },
        {
          id: '3feec5c8-1125-4c66-835f-273ab2f12225',
          name: 'Transfer : Mortgage',
          transfer_account_id: '4f8978af-dc34-4c45-bfda-5fb82925cb93',
          deleted: false
        }
      ],
      payee_locations: [],
      category_groups: [
        {
          id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
          name: 'Internal Master Category',
          hidden: false,
          deleted: false
        },
        {
          id: 'a7d70c70-7ea9-42af-b9d5-f5d155b5ca01',
          name: 'Credit Card Payments',
          hidden: false,
          deleted: false
        },
        {
          id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
          name: 'Immediate Obligations',
          hidden: false,
          deleted: false
        },
        {
          id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'True Expenses',
          hidden: false,
          deleted: false
        },
        {
          id: 'a8236c2d-41d7-4e69-8a37-fb51dbf4c285',
          name: 'Debt Payments',
          hidden: false,
          deleted: false
        },
        {
          id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
          name: 'Quality of Life Goals',
          hidden: false,
          deleted: false
        },
        {
          id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
          name: 'Just for Fun',
          hidden: false,
          deleted: false
        },
        {
          id: '7f0cb1ce-0a1b-4223-bb57-41a2649240e7',
          name: 'Hidden Categories',
          hidden: false,
          deleted: false
        }
      ],
      categories: [
        {
          id: 'c6f17be0-cfeb-4b32-ac71-b1ffad95692e',
          category_group_id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
          name: 'To be Budgeted',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: -2342330,
          balance: -2342330,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'cf51eb84-7413-4406-be5e-3ec63e37483a',
          category_group_id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
          name: 'Deferred Income SubCategory',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'a77965a5-6d14-4403-bfd8-e99e2af501bd',
          category_group_id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
          name: 'Uncategorized',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'ee34e4cb-6a40-4afe-a8e1-ca95f7a96dbf',
          category_group_id: 'a7d70c70-7ea9-42af-b9d5-f5d155b5ca01',
          name: 'American Express',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: null,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'de27df8b-0904-452f-886f-8625842b3561',
          category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
          name: 'Rent/Mortgage',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '1420ab9b-5bac-48dd-81d0-3d9308dbfc99',
          category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
          name: 'Electric',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'a7a75f0c-2a06-42de-91a8-c506bf8c0f7a',
          category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
          name: 'Water',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '461079f6-ade8-4b20-925e-c680108e8d41',
          category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
          name: 'Internet',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '85f57ee3-c11a-4331-9d97-d48c4026a424',
          category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
          name: 'Groceries',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '4091b333-61fa-427d-b99f-bacb57170735',
          category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
          name: 'Transportation',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'e8e297c4-7d8c-446f-9996-661173a144fa',
          category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
          name: 'Interest & Fees',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '6eabc6ba-20ee-4caa-97ea-662032dc0885',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'Auto Maintenance',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'ddcbed06-9dfe-4983-add6-15618a2408bb',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'Home Maintenance',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '5798b35e-8b00-452f-94f4-6bf088d7f4f8',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: "Renter's/Home Insurance",
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'd3a6bf92-a5c8-4c6c-90cb-09e9f76a0430',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'Medical',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '8aa43963-5c34-4fdd-a070-30488e60553f',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'Clothing',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'c4ef2896-9f0a-4caa-b46e-f54f96456434',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'Gifts',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'f029ca42-2c32-476d-9f3f-dc00f3523046',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'Giving',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'fb010c22-65e0-4109-a60e-9bf651cdc99d',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'Computer Replacement',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'f3d1baac-c6a2-44a5-8e8d-086bacf6b0b2',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'Software Subscriptions',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '95b841f4-a632-4cf8-a6d4-dc110e521809',
          category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
          name: 'Stuff I Forgot to Budget For',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '9d9242b7-6afe-4389-9c18-d243e541d5e8',
          category_group_id: 'a8236c2d-41d7-4e69-8a37-fb51dbf4c285',
          name: 'Student Loan',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '90f90c56-7b6a-4006-bad6-6919b2e5ac04',
          category_group_id: 'a8236c2d-41d7-4e69-8a37-fb51dbf4c285',
          name: 'Auto Loan',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '55c9dfcc-16a5-46a0-a42a-ec510e093f23',
          category_group_id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
          name: 'Vacation',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '04b2179f-3960-4f41-a0df-fe75778a65c8',
          category_group_id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
          name: 'Fitness',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'd0733349-6aa4-41e9-8611-ffef1b61fb7e',
          category_group_id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
          name: 'Education',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '54ce766c-1ef0-445e-8ac0-b40c96c84ade',
          category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
          name: 'Dining Out',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '2b12b1fd-26bb-4492-be38-73735d4c74d9',
          category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
          name: 'Gaming',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: '6c2df5aa-d514-4d2b-8c7e-d62e5d2d36a0',
          category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
          name: 'Music',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        },
        {
          id: 'bee18bea-4a12-4f64-a1f7-db7dd4e3a982',
          category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
          name: 'Fun Money',
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 0,
          balance: 0,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: 0,
          deleted: false
        }
      ],
      months: [
        {
          month: '2018-10-01',
          note: null,
          income: 0,
          budgeted: 0,
          activity: 0,
          to_be_budgeted: 0,
          age_of_money: null,
          categories: [
            {
              id: 'fb010c22-65e0-4109-a60e-9bf651cdc99d',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Computer Replacement',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'f3d1baac-c6a2-44a5-8e8d-086bacf6b0b2',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Software Subscriptions',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'f029ca42-2c32-476d-9f3f-dc00f3523046',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Giving',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'ee34e4cb-6a40-4afe-a8e1-ca95f7a96dbf',
              category_group_id: 'a7d70c70-7ea9-42af-b9d5-f5d155b5ca01',
              name: 'American Express',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: null,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'e8e297c4-7d8c-446f-9996-661173a144fa',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Interest & Fees',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'de27df8b-0904-452f-886f-8625842b3561',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Rent/Mortgage',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'ddcbed06-9dfe-4983-add6-15618a2408bb',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Home Maintenance',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'd3a6bf92-a5c8-4c6c-90cb-09e9f76a0430',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Medical',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'd0733349-6aa4-41e9-8611-ffef1b61fb7e',
              category_group_id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
              name: 'Education',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'cf51eb84-7413-4406-be5e-3ec63e37483a',
              category_group_id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
              name: 'Deferred Income SubCategory',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'c6f17be0-cfeb-4b32-ac71-b1ffad95692e',
              category_group_id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
              name: 'Immediate Income SubCategory',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'c4ef2896-9f0a-4caa-b46e-f54f96456434',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Gifts',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'bee18bea-4a12-4f64-a1f7-db7dd4e3a982',
              category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
              name: 'Fun Money',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'a7a75f0c-2a06-42de-91a8-c506bf8c0f7a',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Water',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'a77965a5-6d14-4403-bfd8-e99e2af501bd',
              category_group_id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
              name: 'None',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '9d9242b7-6afe-4389-9c18-d243e541d5e8',
              category_group_id: 'a8236c2d-41d7-4e69-8a37-fb51dbf4c285',
              name: 'Student Loan',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '95b841f4-a632-4cf8-a6d4-dc110e521809',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Stuff I Forgot to Budget For',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '90f90c56-7b6a-4006-bad6-6919b2e5ac04',
              category_group_id: 'a8236c2d-41d7-4e69-8a37-fb51dbf4c285',
              name: 'Auto Loan',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '8aa43963-5c34-4fdd-a070-30488e60553f',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Clothing',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '85f57ee3-c11a-4331-9d97-d48c4026a424',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Groceries',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '6eabc6ba-20ee-4caa-97ea-662032dc0885',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Auto Maintenance',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '6c2df5aa-d514-4d2b-8c7e-d62e5d2d36a0',
              category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
              name: 'Music',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '5798b35e-8b00-452f-94f4-6bf088d7f4f8',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: "Renter's/Home Insurance",
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '55c9dfcc-16a5-46a0-a42a-ec510e093f23',
              category_group_id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
              name: 'Vacation',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '54ce766c-1ef0-445e-8ac0-b40c96c84ade',
              category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
              name: 'Dining Out',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '461079f6-ade8-4b20-925e-c680108e8d41',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Internet',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '4091b333-61fa-427d-b99f-bacb57170735',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Transportation',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '2b12b1fd-26bb-4492-be38-73735d4c74d9',
              category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
              name: 'Gaming',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '1420ab9b-5bac-48dd-81d0-3d9308dbfc99',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Electric',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '04b2179f-3960-4f41-a0df-fe75778a65c8',
              category_group_id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
              name: 'Fitness',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            }
          ]
        },
        {
          month: '2018-10-01',
          note: null,
          income: 0,
          budgeted: 0,
          activity: 0,
          to_be_budgeted: 0,
          age_of_money: null,
          categories: [
            {
              id: 'fb010c22-65e0-4109-a60e-9bf651cdc99d',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Computer Replacement',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'f3d1baac-c6a2-44a5-8e8d-086bacf6b0b2',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Software Subscriptions',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'f029ca42-2c32-476d-9f3f-dc00f3523046',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Giving',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'ee34e4cb-6a40-4afe-a8e1-ca95f7a96dbf',
              category_group_id: 'a7d70c70-7ea9-42af-b9d5-f5d155b5ca01',
              name: 'American Express',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: null,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'e8e297c4-7d8c-446f-9996-661173a144fa',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Interest & Fees',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'de27df8b-0904-452f-886f-8625842b3561',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Rent/Mortgage',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'ddcbed06-9dfe-4983-add6-15618a2408bb',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Home Maintenance',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'd3a6bf92-a5c8-4c6c-90cb-09e9f76a0430',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Medical',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'd0733349-6aa4-41e9-8611-ffef1b61fb7e',
              category_group_id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
              name: 'Education',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'cf51eb84-7413-4406-be5e-3ec63e37483a',
              category_group_id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
              name: 'Deferred Income SubCategory',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'c6f17be0-cfeb-4b32-ac71-b1ffad95692e',
              category_group_id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
              name: 'Immediate Income SubCategory',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'c4ef2896-9f0a-4caa-b46e-f54f96456434',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Gifts',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'bee18bea-4a12-4f64-a1f7-db7dd4e3a982',
              category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
              name: 'Fun Money',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'a7a75f0c-2a06-42de-91a8-c506bf8c0f7a',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Water',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: 'a77965a5-6d14-4403-bfd8-e99e2af501bd',
              category_group_id: '6582164d-35cd-4188-b21a-ce67c1e9181d',
              name: 'None',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '9d9242b7-6afe-4389-9c18-d243e541d5e8',
              category_group_id: 'a8236c2d-41d7-4e69-8a37-fb51dbf4c285',
              name: 'Student Loan',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '95b841f4-a632-4cf8-a6d4-dc110e521809',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Stuff I Forgot to Budget For',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '90f90c56-7b6a-4006-bad6-6919b2e5ac04',
              category_group_id: 'a8236c2d-41d7-4e69-8a37-fb51dbf4c285',
              name: 'Auto Loan',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '8aa43963-5c34-4fdd-a070-30488e60553f',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Clothing',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '85f57ee3-c11a-4331-9d97-d48c4026a424',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Groceries',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '6eabc6ba-20ee-4caa-97ea-662032dc0885',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: 'Auto Maintenance',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '6c2df5aa-d514-4d2b-8c7e-d62e5d2d36a0',
              category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
              name: 'Music',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '5798b35e-8b00-452f-94f4-6bf088d7f4f8',
              category_group_id: 'd91edc28-d298-467f-920e-80fa3ea4ae99',
              name: "Renter's/Home Insurance",
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '55c9dfcc-16a5-46a0-a42a-ec510e093f23',
              category_group_id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
              name: 'Vacation',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '54ce766c-1ef0-445e-8ac0-b40c96c84ade',
              category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
              name: 'Dining Out',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '461079f6-ade8-4b20-925e-c680108e8d41',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Internet',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '4091b333-61fa-427d-b99f-bacb57170735',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Transportation',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '2b12b1fd-26bb-4492-be38-73735d4c74d9',
              category_group_id: '8009650c-6c3a-4b62-9a2d-afec44bd4189',
              name: 'Gaming',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '1420ab9b-5bac-48dd-81d0-3d9308dbfc99',
              category_group_id: 'dbabb326-a3a3-4582-8455-c5d572cff569',
              name: 'Electric',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            },
            {
              id: '04b2179f-3960-4f41-a0df-fe75778a65c8',
              category_group_id: '0dcc8e61-851d-4927-a04b-b2e6d09b7e40',
              name: 'Fitness',
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: 0,
              deleted: false
            }
          ]
        }
      ],
      transactions: [
        {
          id: 'bcc08ac5-2156-457a-ae7d-c71a8ed7f69a',
          date: '2018-08-02',
          amount: -135789000,
          memo: null,
          cleared: 'cleared',
          approved: true,
          flag_color: null,
          account_id: '4f8978af-dc34-4c45-bfda-5fb82925cb93',
          payee_id: 'f3b96458-b9ed-48d4-8781-52a7ef1ad9e4',
          category_id: null,
          transfer_account_id: null,
          import_id: null,
          deleted: false
        },
        {
          id: '4f5e38b5-5472-4a38-9b7f-077250510961',
          date: '2018-08-02',
          amount: -2342330,
          memo: null,
          cleared: 'cleared',
          approved: true,
          flag_color: null,
          account_id: '575ab9b3-d2cc-4e9b-a7fa-c1b9caf937b0',
          payee_id: 'f3b96458-b9ed-48d4-8781-52a7ef1ad9e4',
          category_id: 'c6f17be0-cfeb-4b32-ac71-b1ffad95692e',
          transfer_account_id: null,
          import_id: null,
          deleted: false
        }
      ],
      subtransactions: [],
      scheduled_transactions: [],
      scheduled_subtransactions: []
    },
    server_knowledge: 52
  }
}

describe('Mock Data', () => {
  it('should define all necessary mock data', () => {
    expect(mockYnabBudget).toBeTruthy()
    expect(mockYnoodAccounts).toBeTruthy()
  })
})
